firstName: Aryo
lastName: Yudhanto
hobbies:
  - Gaming
  - Watch movie
  - Coding
address:
  street: Jl. 25 Duren Sawit
  city: Jakarta
  country: Indonesia
wallet:
  - type: cash
    amount: 10000
  - type: debit
    amount: 50000
